### ISSUE TITLE
Can the 1.7 version be released since 1.6 does not work with Grails 2.5.3

### ISSUE THREAD

**Issue by zaccak** [gpc/export#15]
Running the 1.6 version on Grails 2.5.3 results in:

Compilation error: startup failed:
/xxx/target/work/plugins/export-1.6/src/groovy/de/andreasschmitt/export/exporter/ExporterUtil.groovy: 5: unable to resolve class org.apache.commons.beanutils.PropertyUtils
 @ line 5, column 1.
   import org.apache.commons.beanutils.PropertyUtils
   ^
1 error

This is fixed in the 1.7 snapshot over a year ago. Can the 1.7 be released as final? Thanks!

**Comment by frangarcia** [comment]
It would be nice to hace 1.7 released when possible but in the meantime, if you want to use the plugin with 2.5.3, please try to use the snapshot version of the plugin.

```
grails.project.dependency.resolution = {
  ...

  repositories {
    ...
    mavenRepo "http://repo.grails.org/grails/core"
  }

  dependencies {
    ...
    compile 'commons-beanutils:commons-beanutils:1.8.3'
  }
  plugins {
    ...
    compile ":export:1.7-SNAPSHOT"
  }
}
```

Let me know if that works for you.

**Comment by zaccak** [comment]
The snapshot works without the:
  dependencies {
    ...
    compile 'commons-beanutils:commons-beanutils:1.8.3'
  }

**Comment by frangarcia** [comment]
Good to know it. Thanks!

**Comment by daptordarattler** [comment]
1.6 works with Grails 2.5.3
Just add this in your repository section
```
repositories {
...
      mavenRepo "http://repo.grails.org/grails/core"
}
```

1.7 actually has a bug where the auto export is expect the parameter 'format' but then 'f' is used. It needs to change to format since in the sample code that's actually what is being expected

**Comment by psnehal** [comment]
Any chance that it will work with grails 3?

**Comment by jeffbrown** [comment]
> Any chance that it will work with grails 3?

@psnehal It depends on what you mean by "it".  There is a version of the `export` plugin for Grails 3.  https://bintray.com/grails/plugins/org.grails.plugins:export

**Comment by psnehal** [comment]
Hello Jeff:

Thank you for replying. i had trouble finding link for this plugin. So In build.gradle which version I should mention. Only complie doesn't work. compile "org.grails.plugins:export"

Thanks
Snehal

**Comment by psnehal** [comment]
Thank you Jeff for replying. I was adding different version no. Now its works.

**Comment by psnehal** [comment]
Adding   def grailsApplication  in controller gives following error. 
Please let me know if you know anything about this error:

ERROR grails.boot.GrailsApp - Compilation Error: startup failed:
my-app/grails-app/controllers/testconsig1/Fileup1Controller.groovy: -1: The return type of java.lang.Object getGrailsApplication() in testconsig1.Fileup1Controller is incompatible with grails.core.GrailsApplication in grails.web.api.WebAttributes
. At [-1:-1]  @ line -1, column -1.
1 error

**Comment by burtbeckwith** [comment]
Controllers in Grails 2 and Grails 3 already have an implicit dependency injection for `GrailsApplication`, so you're adding a second. In Grails 2 it's not typed (`def grailsApplication`) but in Grails 3 it is typed (`GrailsApplication grailsApplication`), so you've effectively added an override, but with a less specific return type which is invalid. Just delete your `def grailsApplication` and use the one that's already there.

**Comment by miq** [comment]
We have releases for Grails 3.x to 6.x and a fresh one for Grails 7+. There is no work planned for Grails 2.x as it is obsolete for a very long time.

If there is extreme pressure for a Grails 2.x release, this could be reopened.
